<?php
$file = 'c:\xampp\htdocs\JDH_POS\src\functions.php';
$content = file_get_contents($file);

// 1. Optimize check_permission with static caching
$old = "    function check_permission(string \$permission_code): bool\r\n    {\r\n        \$permission_code = sanitize_input(\$permission_code, 'alphanumeric');\r\n        \r\n        // Super admin has all permissions\r\n        if (function_exists('is_super_admin') && is_super_admin()) {\r\n            return true;\r\n        }\r\n        \r\n        // Check session permissions\r\n        if (isset(\$_SESSION['permissions']) && is_array(\$_SESSION['permissions'])) {\r\n            if (in_array(\$permission_code, \$_SESSION['permissions'], true)) {\r\n                return true;\r\n            }\r\n        }\r\n        \r\n        if (isset(\$_SESSION['user_permissions']) && is_array(\$_SESSION['user_permissions'])) {\r\n            if (in_array(\$permission_code, \$_SESSION['user_permissions'], true)) {\r\n                return true;\r\n            }\r\n        }\r\n        \r\n        // Check for wildcard permissions\r\n        \$wildcardPattern = str_replace('*', '.*', \$permission_code);\r\n        \$wildcardPattern = '/^' . str_replace('/', '\\\\/', \$wildcardPattern) . '$/';\r\n        \r\n        \$allPermissions = array_merge(\r\n            \$_SESSION['permissions'] ?? [],\r\n            \$_SESSION['user_permissions'] ?? []\r\n        );\r\n        \r\n        foreach (\$allPermissions as \$perm) {\r\n            if (str_contains(\$perm, '*')) {\r\n                \$pattern = '/^' . str_replace('*', '.*', str_replace('/', '\\\\/', \$perm)) . '$/';\r\n                if (preg_match(\$pattern, \$permission_code)) {\r\n                    return true;\r\n                }\r\n            }\r\n        }\r\n\r\n        return false;\r\n    }";

$new = "    function check_permission(string \$permission_code): bool\r\n    {\r\n        static \$cache = [];\r\n        static \$wildcardChecked = false;\r\n        static \$wildcardCache = [];\r\n\r\n        \$permission_code = sanitize_input(\$permission_code, 'alphanumeric');\r\n\r\n        if (isset(\$cache[\$permission_code])) {\r\n            return \$cache[\$permission_code];\r\n        }\r\n\r\n        if (function_exists('is_super_admin') && is_super_admin()) {\r\n            \$cache[\$permission_code] = true;\r\n            return true;\r\n        }\r\n\r\n        if (isset(\$_SESSION['permissions']) && is_array(\$_SESSION['permissions'])) {\r\n            if (in_array(\$permission_code, \$_SESSION['permissions'], true)) {\r\n                \$cache[\$permission_code] = true;\r\n                return true;\r\n            }\r\n        }\r\n\r\n        if (isset(\$_SESSION['user_permissions']) && is_array(\$_SESSION['user_permissions'])) {\r\n            if (in_array(\$permission_code, \$_SESSION['user_permissions'], true)) {\r\n                \$cache[\$permission_code] = true;\r\n                return true;\r\n            }\r\n        }\r\n\r\n        if (!\$wildcardChecked) {\r\n            \$allPermissions = array_merge(\r\n                \$_SESSION['permissions'] ?? [],\r\n                \$_SESSION['user_permissions'] ?? []\r\n            );\r\n            foreach (\$allPermissions as \$perm) {\r\n                if (str_contains(\$perm, '*')) {\r\n                    \$wildcardCache[] = '/^' . str_replace('*', '.*', str_replace('/', '\\\\/', \$perm)) . '$/';\r\n                }\r\n            }\r\n            \$wildcardChecked = true;\r\n        }\r\n\r\n        foreach (\$wildcardCache as \$pattern) {\r\n            if (preg_match(\$pattern, \$permission_code)) {\r\n                \$cache[\$permission_code] = true;\r\n                return true;\r\n            }\r\n        }\r\n\r\n        \$cache[\$permission_code] = false;\r\n        return false;\r\n    }";

if (strpos($content, $old) !== false) {
    $content = str_replace($old, $new, $content);
    echo "check_permission optimized\n";
} else {
    echo "check_permission pattern not found\n";
}

// 2. Optimize get_settings with session caching
$old2 = "        if (empty(\$cache) && function_exists('db_fetch_all')) {\r\n            try {\r\n                \$rows = db_fetch_all(\r\n                    \"SELECT setting_key, setting_value FROM settings WHERE tenant_id = ?\",\r\n                    [\$tenant_id]\r\n                );\r\n                foreach (\$rows as \$row) {\r\n                    \$cache[\$row['setting_key']] = \$row['setting_value'];\r\n                }\r\n            } catch (Exception \$e) {\r\n                error_log(\"Failed to fetch settings: \" . \$e->getMessage());\r\n            }\r\n        }\r\n        \r\n        if (\$key !== null) {\r\n            return \$cache[\$key] ?? \$default;\r\n        }\r\n        return \$cache;\r\n    }";

$new2 = "        // Use session cache for cross-request persistence (30-second TTL)\r\n        \$sessionKey = '_settings_' . \$tenant_id;\r\n        if (empty(\$cache) && isset(\$_SESSION[\$sessionKey]) && (time() - (\$_SESSION[\$sessionKey . '_time'] ?? 0) < 30)) {\r\n            \$cache = \$_SESSION[\$sessionKey];\r\n        }\r\n\r\n        if (empty(\$cache) && function_exists('db_fetch_all')) {\r\n            try {\r\n                \$rows = db_fetch_all(\r\n                    \"SELECT setting_key, setting_value FROM settings WHERE tenant_id = ?\",\r\n                    [\$tenant_id]\r\n                );\r\n                foreach (\$rows as \$row) {\r\n                    \$cache[\$row['setting_key']] = \$row['setting_value'];\r\n                }\r\n                \$_SESSION[\$sessionKey] = \$cache;\r\n                \$_SESSION[\$sessionKey . '_time'] = time();\r\n            } catch (Exception \$e) {\r\n                error_log(\"Failed to fetch settings: \" . \$e->getMessage());\r\n            }\r\n        }\r\n\r\n        if (\$key !== null) {\r\n            return \$cache[\$key] ?? \$default;\r\n        }\r\n        return \$cache;\r\n    }";

if (strpos($content, $old2) !== false) {
    $content = str_replace($old2, $new2, $content);
    echo "get_settings optimized\n";
} else {
    echo "get_settings pattern not found\n";
}

file_put_contents($file, $content);
echo "Done\n";
