-- ========================================================
-- Data Migration: permissions
-- Database: jdh_pos
-- Row Count: 153
-- Generated: 2026-06-24 05:23:37
-- ========================================================

SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE `permissions`;

INSERT INTO `permissions` (`id`, `code`, `description`, `module`, `tenant_id`, `category`, `deleted_at`) VALUES
('1', 'pos.view', 'Access the POS screen', 'pos', '1', 'pos', NULL),
('2', 'pos.sell', 'Create sales transactions', 'pos', '1', 'pos', NULL),
('3', 'pos.refund', 'Issue refunds and returns', 'pos', '1', 'pos', NULL),
('4', 'pos.discount', 'Apply discounts at checkout', 'pos', '1', 'pos', NULL),
('5', 'pos.hold', 'Park and retrieve held orders', 'pos', '1', 'pos', NULL),
('6', 'pos.order', 'Create and manage customer orders', 'pos', '1', 'pos', NULL),
('7', 'pos.split', 'Split bill between customers', 'pos', '1', 'pos', NULL),
('8', 'pos.table', 'Manage restaurant tables', 'pos', '1', 'pos', NULL),
('9', 'pos.kitchen', 'Send and manage kitchen orders', 'pos', '1', 'pos', NULL),
('10', 'sales.view', 'Access sales history', 'sales', '1', 'sales', NULL),
('11', 'sales.manage', 'Edit and void sales', 'sales', '1', 'sales', NULL),
('12', 'sales.export', 'Export sales data', 'sales', '1', 'sales', NULL),
('13', 'sales.returns', 'Handle product returns', 'sales', '1', 'sales', NULL),
('14', 'products.view', 'Browse product catalog', 'products', '1', 'products', NULL),
('15', 'products.create', 'Add new products', 'products', '1', 'products', NULL),
('16', 'products.edit', 'Modify product details', 'products', '1', 'products', NULL),
('17', 'products.delete', 'Remove products from catalog', 'products', '1', 'products', NULL),
('18', 'products.import', 'Bulk import products', 'products', '1', 'products', NULL),
('19', 'products.categories', 'Organize product categories', 'products', '1', 'products', NULL),
('20', 'products.pricing', 'Set product prices and tiers', 'products', '1', 'products', NULL),
('21', 'inventory.view', 'Check stock levels', 'inventory', '1', 'inventory', NULL),
('22', 'inventory.adjust', 'Manual stock adjustments', 'inventory', '1', 'inventory', NULL),
('23', 'inventory.transfer', 'Transfer stock between locations', 'inventory', '1', 'inventory', NULL),
('24', 'inventory.count', 'Perform stock takes', 'inventory', '1', 'inventory', NULL),
('25', 'inventory.reorder', 'Set reorder thresholds', 'inventory', '1', 'inventory', NULL),
('26', 'inventory.alerts', 'View and manage stock alerts', 'inventory', '1', 'inventory', NULL),
('27', 'customers.view', 'Access customer list', 'customers', '1', 'customers', NULL),
('28', 'customers.create', 'Add new customers', 'customers', '1', 'customers', NULL),
('29', 'customers.edit', 'Update customer information', 'customers', '1', 'customers', NULL),
('30', 'customers.delete', 'Remove customer records', 'customers', '1', 'customers', NULL),
('31', 'customers.loyalty', 'Manage loyalty points and rewards', 'customers', '1', 'customers', NULL),
('32', 'customers.credit', 'Manage customer credit accounts', 'customers', '1', 'customers', NULL),
('33', 'users.view', 'Access staff/user list', 'users', '1', 'users', NULL),
('34', 'users.create', 'Add new staff members', 'users', '1', 'users', NULL),
('35', 'users.edit', 'Update user information', 'users', '1', 'users', NULL),
('36', 'users.delete', 'Remove user accounts', 'users', '1', 'users', NULL),
('37', 'users.roles', 'Create and assign roles', 'users', '1', 'users', NULL),
('38', 'users.attendance', 'Track staff attendance', 'users', '1', 'users', NULL),
('39', 'reports.view', 'Access all reports', 'reports', '1', 'reports', NULL),
('40', 'reports.sales', 'View sales analytics', 'reports', '1', 'reports', NULL),
('41', 'reports.inventory', 'View stock and inventory reports', 'reports', '1', 'reports', NULL),
('42', 'reports.financial', 'View profit and loss statements', 'reports', '1', 'reports', NULL),
('43', 'reports.profit', 'View profit margins by product', 'reports', '1', 'reports', NULL),
('44', 'reports.tax', 'View tax collection summaries', 'reports', '1', 'reports', NULL),
('45', 'reports.export', 'Export report data', 'reports', '1', 'reports', NULL),
('46', 'reports.expense', 'Track and report expenses', 'reports', '1', 'reports', NULL),
('47', 'reports.dashboard', 'View main dashboard analytics', 'reports', '1', 'reports', NULL),
('48', 'expenses.view', 'Access expense records', 'expenses', '1', 'expenses', NULL),
('49', 'expenses.create', 'Record new expenses', 'expenses', '1', 'expenses', NULL),
('50', 'expenses.edit', 'Modify expense entries', 'expenses', '1', 'expenses', NULL),
('51', 'expenses.categories', 'Manage expense categories', 'expenses', '1', 'expenses', NULL),
('52', 'expenses.approve', 'Approve pending expenses', 'expenses', '1', 'expenses', NULL),
('53', 'settings.view', 'Access system settings', 'settings', '1', 'settings', NULL),
('54', 'settings.general', 'Manage store information', 'settings', '1', 'settings', NULL),
('55', 'settings.payment', 'Configure payment options', 'settings', '1', 'settings', NULL),
('56', 'settings.tax', 'Manage tax rates and rules', 'settings', '1', 'settings', NULL),
('57', 'settings.receipt', 'Customize receipt templates', 'settings', '1', 'settings', NULL),
('58', 'settings.backup', 'Manage system backups', 'settings', '1', 'settings', NULL),
('59', 'settings.api', 'Manage API keys and webhooks', 'settings', '1', 'settings', NULL),
('60', 'branch.view', 'Access branch locations', 'branch', '1', 'branch', NULL),
('61', 'branch.create', 'Add new branch locations', 'branch', '1', 'branch', NULL),
('62', 'branch.manage', 'Edit branch settings', 'branch', '1', 'branch', NULL),
('63', 'branch.transfer', 'Transfer between branches', 'branch', '1', 'branch', NULL),
('64', 'branch.reports', 'View branch performance', 'branch', '1', 'branch', NULL),
('65', 'kitchen.view', 'Access kitchen display', 'kitchen', '1', 'kitchen', NULL),
('66', 'kitchen.send', 'Submit orders to kitchen', 'kitchen', '1', 'kitchen', NULL),
('67', 'kitchen.ready', 'Mark items as ready', 'kitchen', '1', 'kitchen', NULL),
('68', 'kitchen.manage', 'Manage kitchen workflow', 'kitchen', '1', 'kitchen', NULL),
('69', 'delivery.view', 'Access delivery orders', 'delivery', '1', 'delivery', NULL),
('70', 'delivery.assign', 'Assign riders to orders', 'delivery', '1', 'delivery', NULL),
('71', 'delivery.update', 'Update delivery status', 'delivery', '1', 'delivery', NULL),
('72', 'delivery.track', 'Track live delivery status', 'delivery', '1', 'delivery', NULL),
('73', 'orders.view', 'Access all orders', 'orders', '1', 'orders', NULL),
('74', 'orders.dispatch', 'Dispatch orders for delivery', 'orders', '1', 'orders', NULL),
('75', 'orders.cancel', 'Cancel pending orders', 'orders', '1', 'orders', NULL),
('76', 'orders.modify', 'Edit existing orders', 'orders', '1', 'orders', NULL),
('77', 'dispatch.view', 'Access dispatch board', 'dispatch', '1', 'dispatch', NULL),
('78', 'dispatch.assign', 'Assign dispatch tasks', 'dispatch', '1', 'dispatch', NULL),
('79', 'dispatch.route', 'Plan delivery routes', 'dispatch', '1', 'dispatch', NULL),
('80', 'attendance.view', 'Check staff attendance', 'attendance', '1', 'attendance', NULL),
('81', 'attendance.clock', 'Record attendance', 'attendance', '1', 'attendance', NULL),
('82', 'attendance.manage', 'Edit attendance records', 'attendance', '1', 'attendance', NULL),
('83', 'attendance.leave', 'Manage leave applications', 'attendance', '1', 'attendance', NULL),
('84', 'dashboard.view', 'View Dashboard', 'core', '1', 'general', NULL),
('85', 'pos.access', 'Access Point of Sale', 'core', '1', 'general', NULL),
('86', 'sales.create', 'Create Sales', 'core', '1', 'general', NULL),
('93', 'profile.view', 'View Profile', 'core', '1', 'general', NULL),
('94', 'profile.edit', 'Edit Profile', 'core', '1', 'general', NULL),
('99', 'sales.edit', 'Edit Sales', 'core', '1', 'general', NULL),
('100', 'sales.delete', 'Delete Sales', 'core', '1', 'general', NULL),
('102', 'sales.refunds', 'Process Refunds', 'core', '1', 'general', NULL),
('103', 'sales.discounts', 'Manage Discounts', 'core', '1', 'general', NULL),
('104', 'sales.vouchers', 'Manage Vouchers', 'core', '1', 'general', NULL),
('109', 'products.manage', 'Manage Product Attributes', 'core', '1', 'general', NULL),
('110', 'products.export', 'Export Products', 'core', '1', 'general', NULL),
('112', 'brands.view', 'View Brands', 'core', '1', 'general', NULL),
('113', 'brands.create', 'Create Brands', 'core', '1', 'general', NULL),
('114', 'brands.edit', 'Edit Brands', 'core', '1', 'general', NULL),
('115', 'brands.delete', 'Delete Brands', 'core', '1', 'general', NULL),
('116', 'categories.view', 'View Categories', 'core', '1', 'general', NULL),
('117', 'categories.create', 'Create Categories', 'core', '1', 'general', NULL),
('118', 'categories.edit', 'Edit Categories', 'core', '1', 'general', NULL),
('119', 'categories.delete', 'Delete Categories', 'core', '1', 'general', NULL),
('121', 'inventory.manage', 'Manage Inventory', 'core', '1', 'general', NULL),
('124', 'inventory.expiry', 'Manage Expiry Tracking', 'core', '1', 'general', NULL),
('125', 'suppliers.view', 'View Suppliers', 'core', '1', 'general', NULL),
('126', 'suppliers.create', 'Create Suppliers', 'core', '1', 'general', NULL),
('127', 'suppliers.edit', 'Edit Suppliers', 'core', '1', 'general', NULL),
('128', 'suppliers.delete', 'Delete Suppliers', 'core', '1', 'general', NULL),
('133', 'customers.bulk_sms', 'Send Bulk SMS', 'core', '1', 'general', NULL),
('134', 'purchases.view', 'View Purchases', 'core', '1', 'general', NULL),
('135', 'purchases.create', 'Create Purchases', 'core', '1', 'general', NULL),
('136', 'purchases.edit', 'Edit Purchases', 'core', '1', 'general', NULL),
('137', 'purchases.approve', 'Approve Purchases', 'core', '1', 'general', NULL),
('138', 'shipments.view', 'View Shipments', 'core', '1', 'general', NULL),
('139', 'shipments.create', 'Create Shipments', 'core', '1', 'general', NULL),
('140', 'shipments.edit', 'Edit Shipments', 'core', '1', 'general', NULL),
('141', 'shipments.receive', 'Receive Shipments', 'core', '1', 'general', NULL),
('151', 'users.manage', 'Manage Users', 'core', '1', 'general', NULL),
('152', 'roles.view', 'View Roles', 'core', '1', 'general', NULL),
('153', 'roles.create', 'Create Roles', 'core', '1', 'general', NULL),
('154', 'roles.edit', 'Edit Roles', 'core', '1', 'general', NULL),
('155', 'roles.delete', 'Delete Roles', 'core', '1', 'general', NULL),
('156', 'roles.assign', 'Assign Roles', 'core', '1', 'general', NULL),
('157', 'branches.view', 'View Branches', 'core', '1', 'general', NULL),
('158', 'branches.create', 'Create Branches', 'core', '1', 'general', NULL),
('159', 'branches.edit', 'Edit Branches', 'core', '1', 'general', NULL),
('160', 'branches.delete', 'Delete Branches', 'core', '1', 'general', NULL),
('161', 'branches.manage', 'Manage Branches', 'core', '1', 'general', NULL),
('162', 'system.settings', 'Access System Settings', 'core', '1', 'general', NULL),
('163', 'system.backup', 'Perform Backup', 'core', '1', 'general', NULL),
('164', 'system.restore', 'Perform Restore', 'core', '1', 'general', NULL),
('165', 'system.logs', 'View System Logs', 'core', '1', 'general', NULL),
('166', 'system.maintenance', 'System Maintenance', 'core', '1', 'general', NULL),
('167', 'billing.view', 'View Billing', 'core', '1', 'general', NULL),
('168', 'billing.manage', 'Manage Billing', 'core', '1', 'general', NULL),
('169', 'billing.settings', 'Billing Settings', 'core', '1', 'general', NULL),
('170', 'crm.view', 'Access CRM', 'core', '1', 'general', NULL),
('171', 'crm.leads', 'Manage CRM Leads', 'core', '1', 'general', NULL),
('172', 'crm.deals', 'Manage CRM Deals', 'core', '1', 'general', NULL),
('173', 'hr.view', 'Access HR', 'core', '1', 'general', NULL),
('174', 'hr.employees', 'Manage Employees', 'core', '1', 'general', NULL),
('175', 'hr.leaves', 'Manage Leave Requests', 'core', '1', 'general', NULL),
('176', 'hr.payroll', 'Manage Payroll', 'core', '1', 'general', NULL),
('177', 'loyalty.view', 'View Loyalty Program', 'core', '1', 'general', NULL),
('178', 'loyalty.manage', 'Manage Loyalty Program', 'core', '1', 'general', NULL),
('179', 'marketing.sms', 'Send Marketing SMS', 'core', '1', 'general', NULL),
('180', 'marketing.email', 'Send Marketing Emails', 'core', '1', 'general', NULL),
('183', 'quotations.view', 'View Quotations', 'core', '1', 'general', NULL),
('184', 'quotations.create', 'Create Quotations', 'core', '1', 'general', NULL),
('185', 'quotations.edit', 'Edit Quotations', 'core', '1', 'general', NULL),
('186', 'quotations.delete', 'Delete Quotations', 'core', '1', 'general', NULL),
('190', 'expenses.delete', 'Delete Expenses', 'core', '1', 'general', NULL);

SET FOREIGN_KEY_CHECKS=1;
